<?php
/**
 * Footer Template
 */
?>
<footer class="site-footer">
    <div class="container">
        <div class="footer-grid">
            <div class="footer-column">
                <h3>Berg Projects</h3>
                <p>Building South Africa's future with excellence and innovation since 2009.</p>
            </div>
            <div class="footer-column">
                <h3>Services</h3>
                <ul>
                    <li><a href="#services-section">Construction Management</a></li>
                    <li><a href="#services-section">Project Management</a></li>
                    <li><a href="#services-section">Property Development</a></li>
                </ul>
            </div>
            <div class="footer-column">
                <h3>Company</h3>
                <ul>
                    <li><a href="#why-choose-section">About Us</a></li>
                    <li><a href="#testimonial-section">Testimonials</a></li>
                    <li><a href="#contact-section">Contact</a></li>
                </ul>
            </div>
            <div class="footer-column">
                <h3>Contact</h3>
                <p><strong>Phone:</strong> <a href="tel:+27833249054" style="color: #cbd5e1;">083 324 9054</a><br>
                <strong>Email:</strong> <a href="mailto:marius@bergpartnerships.co.za" style="color: #cbd5e1;">marius@bergpartnerships.co.za</a><br>
                <strong>Location:</strong> Pretoria, Gauteng</p>
            </div>
        </div>
        <div class="footer-bottom">
            <p>&copy; <?php echo date('Y'); ?> Berg Projects. All rights reserved. | Generated by ReactorBro Stack AI Agents</p>
        </div>
    </div>
</footer>
<?php wp_footer(); ?>
</body>
</html>
